'use client'

import { useState, useEffect, useRef, useMemo } from 'react'
import { Check } from 'lucide-react'

/* ── Live Build Studio ─────────────────────────────────────────────
   Cinematic generation overlay: a "4K live recording" of the AI
   writing the website's code word-by-word, with a browser preview
   that assembles itself in sync. Each loop of the script renders a
   different design style (Modern → Minimal → Bold) to mirror the
   real backend pipeline steps. Real progress % / job id / stale
   warning are passed in from the polling loop in page.tsx. */

type ScriptLine = { file: number; text: string; stage?: string }

const FILES = ['index.html', 'styles.css', 'app.js']

const STYLES = [
  { name: 'Modern', accent: '#6B5CFF', glow: 'rgba(107,92,255,.5)', heroFrom: '#1A1440', heroTo: '#0F0F1A' },
  { name: 'Minimal', accent: '#22C08F', glow: 'rgba(34,192,143,.45)', heroFrom: '#0E2A22', heroTo: '#0F0F1A' },
  { name: 'Bold', accent: '#FF6B4A', glow: 'rgba(255,107,74,.45)', heroFrom: '#3A160E', heroTo: '#0F0F1A' },
]

const TICKER = [
  'Analyzing brand tone…',
  'Choosing a typography pair…',
  'Balancing the color palette…',
  'Laying out the hero section…',
  'Optimizing for mobile screens…',
  'Compressing images to WebP…',
  'Wiring the WhatsApp button…',
  'Injecting SEO meta tags…',
  'Tuning contrast for readability…',
  'Rounding corners, adding glow…',
  'Testing tap targets…',
  'Polishing micro-animations…',
]

function deriveName(hint?: string): string {
  if (!hint) return 'Your Business'
  const words = hint.trim().split(/\s+/).slice(0, 3).filter(w => /^[\p{L}\p{N}'&-]+$/u.test(w))
  if (!words.length) return 'Your Business'
  return words.map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ').slice(0, 26)
}

function buildScript(name: string, styleName: string, accent: string): ScriptLine[] {
  const h: ScriptLine[] = [
    { file: 0, text: '<!DOCTYPE html>' },
    { file: 0, text: `<!-- ${styleName} style · generated by binaapp AI -->` },
    { file: 0, text: '<html lang="ms">' },
    { file: 0, text: '<head>' },
    { file: 0, text: '  <meta charset="UTF-8" />' },
    { file: 0, text: '  <meta name="viewport" content="width=device-width" />' },
    { file: 0, text: `  <title>${name} — Official Website</title>` },
    { file: 0, text: `  <meta name="theme-color" content="${accent}" />` },
    { file: 0, text: '  <link rel="stylesheet" href="styles.css" />' },
    { file: 0, text: '</head>' },
    { file: 0, text: '<body>' },
    { file: 0, text: '  <nav class="navbar glass">' },
    { file: 0, text: `    <span class="logo">${name}</span>` },
    { file: 0, text: '    <a href="#menu">Menu</a> <a href="#about">About</a>' },
    { file: 0, text: '    <a href="#contact" class="pill">Order Now</a>' },
    { file: 0, text: '  </nav>', stage: 'nav' },
    { file: 0, text: '' },
    { file: 0, text: '  <header class="hero">' },
    { file: 0, text: `    <h1>Welcome to ${name}</h1>`, stage: 'heroTitle' },
    { file: 0, text: '    <p>Fresh. Local. Delivered to your door.</p>', stage: 'heroText' },
    { file: 0, text: '    <button class="cta">Order via WhatsApp</button>', stage: 'cta' },
    { file: 0, text: '  </header>', stage: 'hero' },
    { file: 0, text: '' },
    { file: 0, text: '  <section id="menu" class="cards">' },
    { file: 0, text: '    <article class="card"><img /><h3>Signature</h3></article>', stage: 'card1' },
    { file: 0, text: '    <article class="card"><img /><h3>Best Seller</h3></article>', stage: 'card2' },
    { file: 0, text: '    <article class="card"><img /><h3>New Arrival</h3></article>', stage: 'card3' },
    { file: 0, text: '  </section>' },
    { file: 0, text: '' },
    { file: 0, text: '  <section id="contact" class="contact">' },
    { file: 0, text: '    <input placeholder="Your name" />' },
    { file: 0, text: '    <input placeholder="Phone number" />' },
    { file: 0, text: '    <button class="send">Send Message</button>', stage: 'contact' },
    { file: 0, text: '  </section>' },
    { file: 0, text: '' },
    { file: 0, text: `  <footer>© ${new Date().getFullYear()} ${name} · Built with binaapp</footer>`, stage: 'footer' },
    { file: 0, text: '</body>' },
    { file: 0, text: '</html>' },
  ]
  const c: ScriptLine[] = [
    { file: 1, text: `/* ${styleName} theme — auto-tuned palette */` },
    { file: 1, text: ':root {' },
    { file: 1, text: `  --accent: ${accent};` },
    { file: 1, text: '  --bg: #0B0B14; --ink: #F5F5FA;' },
    { file: 1, text: '}' },
    { file: 1, text: '.navbar {' },
    { file: 1, text: '  position: sticky; top: 0;' },
    { file: 1, text: '  backdrop-filter: blur(18px);' },
    { file: 1, text: '}' },
    { file: 1, text: '.hero {' },
    { file: 1, text: '  min-height: 82vh;' },
    { file: 1, text: '  background: radial-gradient(var(--accent), transparent);' },
    { file: 1, text: '  animation: fade-up .8s ease both;', stage: 'polish1' },
    { file: 1, text: '}' },
    { file: 1, text: '.cta {' },
    { file: 1, text: '  background: var(--accent);' },
    { file: 1, text: '  box-shadow: 0 0 32px var(--accent);' },
    { file: 1, text: '  border-radius: 999px;', stage: 'polish2' },
    { file: 1, text: '}' },
    { file: 1, text: '.card { border-radius: 18px; transition: transform .3s; }' },
    { file: 1, text: '.card:hover { transform: translateY(-6px); }', stage: 'polish3' },
    { file: 1, text: '@media (max-width: 640px) {' },
    { file: 1, text: '  .cards { grid-template-columns: 1fr; }' },
    { file: 1, text: '}' },
  ]
  const j: ScriptLine[] = [
    { file: 2, text: `// interactivity — ${styleName.toLowerCase()} build` },
    { file: 2, text: "const cta = document.querySelector('.cta')" },
    { file: 2, text: 'cta.addEventListener("click", () => {' },
    { file: 2, text: `  window.open('https://wa.me/60123456789')` },
    { file: 2, text: '})' },
    { file: 2, text: '' },
    { file: 2, text: 'const observer = new IntersectionObserver((entries) => {' },
    { file: 2, text: "  entries.forEach(e => e.target.classList.add('visible'))" },
    { file: 2, text: '}, { threshold: 0.2 })' },
    { file: 2, text: "document.querySelectorAll('.card').forEach(c => observer.observe(c))" },
    { file: 2, text: '' },
    { file: 2, text: '// ✓ build complete — deploying preview', stage: 'done' },
  ]
  return [...h, ...c, ...j]
}

/* Lightweight syntax highlighting per file type */
function highlight(text: string, file: number, accent: string) {
  const re =
    file === 0
      ? /(<\/?[a-zA-Z][\w-]*|\/?>|"[^"]*"|<!--[\s\S]*?-->|<!DOCTYPE html>)/g
      : file === 1
        ? /(\/\*[\s\S]*?\*\/|[.#:][\w-]+(?=[\s,{:]|$)|--[\w-]+|@media|\{|\}|"[^"]*")/g
        : /(\/\/.*$|\bconst\b|\blet\b|\bnew\b|\bwindow\b|\bdocument\b|=>|'[^']*'|"[^"]*"|`[^`]*`)/g
  const parts = text.split(re)
  return parts.map((p, i) => {
    if (!p) return null
    let color = '#B8C0E0'
    if (/^(<!--|\/\/|\/\*|<!DOCTYPE)/.test(p)) color = '#4A4A5E'
    else if (/^<\/?[a-zA-Z]/.test(p) || p === '>' || p === '/>') color = '#9D8CFF'
    else if (/^["'`]/.test(p)) color = '#A6E22E'
    else if (/^[.#:@-]|^--/.test(p) && file === 1) color = accent
    else if (/^(const|let|new|window|document|=>)$/.test(p)) color = '#7DCFFF'
    else if (p === '{' || p === '}') color = '#FFB020'
    return <span key={i} style={{ color }}>{p}</span>
  })
}

const REAL_STEPS = [
  { label: 'Analyzing your business description', start: 10, end: 30 },
  { label: 'Generating Modern style', start: 30, end: 50 },
  { label: 'Generating Minimal style', start: 50, end: 70 },
  { label: 'Generating Bold style', start: 70, end: 90 },
  { label: 'Finalizing website', start: 90, end: 100 },
]

interface Props {
  progress: number
  jobId?: string | null
  staleWarning: boolean
  businessHint?: string
}

export default function LiveBuildStudio({ progress, jobId, staleWarning, businessHint }: Props) {
  const name = useMemo(() => deriveName(businessHint), [businessHint])
  const [loop, setLoop] = useState(0)
  const [li, setLi] = useState(0)
  const [ci, setCi] = useState(0)
  const [stages, setStages] = useState<string[]>([])
  const [tick, setTick] = useState(0)
  const [flash, setFlash] = useState(false)

  const startRef = useRef<number>(Date.now())
  const charsRef = useRef(0)
  const linesRef = useRef(0)
  const scrollRef = useRef<HTMLDivElement>(null)

  const style = STYLES[loop % STYLES.length]
  const script = useMemo(() => buildScript(name, style.name, style.accent), [name, style])

  /* HUD clock — drives timecode, ticker and stat refresh */
  useEffect(() => {
    const id = setInterval(() => setTick(t => t + 1), 120)
    return () => clearInterval(id)
  }, [])

  /* Typing engine — chunked chars for an AI-streaming feel */
  useEffect(() => {
    if (li >= script.length) {
      const t = setTimeout(() => {
        setFlash(true)
        setTimeout(() => setFlash(false), 350)
        setStages([])
        setLi(0)
        setCi(0)
        setLoop(l => l + 1)
      }, 1800)
      return () => clearTimeout(t)
    }
    const line = script[li]
    if (ci < line.text.length) {
      const t = setTimeout(() => {
        const step = 2 + ((li + ci) % 2)
        charsRef.current += Math.min(step, line.text.length - ci)
        setCi(c => Math.min(line.text.length, c + step))
      }, 16 + ((li * 7 + ci) % 3) * 9)
      return () => clearTimeout(t)
    }
    const t = setTimeout(() => {
      linesRef.current += 1
      if (line.stage) {
        const s = line.stage
        setStages(prev => (prev.includes(s) ? prev : [...prev, s]))
      }
      setLi(i => i + 1)
      setCi(0)
    }, line.text === '' ? 40 : 100)
    return () => clearTimeout(t)
  }, [li, ci, script])

  /* Keep editor pinned to the latest line */
  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight })
  }, [li, ci])

  const safeLi = Math.min(li, script.length - 1)
  const currentFile = script[safeLi].file
  const fileLines: { no: number; text: string; partial: boolean }[] = []
  let no = 0
  for (let i = 0; i < script.length; i++) {
    if (script[i].file !== currentFile) continue
    no += 1
    if (i < li) fileLines.push({ no, text: script[i].text, partial: false })
    else if (i === li) { fileLines.push({ no, text: script[i].text.slice(0, ci), partial: true }); break }
    else break
  }
  const visible = fileLines.slice(-13)

  const elapsed = (tick * 120) / 1000
  const mm = String(Math.floor(elapsed / 60)).padStart(2, '0')
  const ss = String(Math.floor(elapsed % 60)).padStart(2, '0')
  const ff = String(Math.floor((elapsed % 1) * 24)).padStart(2, '0')
  const tokPerSec = elapsed > 1 ? Math.round((charsRef.current / elapsed) / 3.2) : 0
  const has = (s: string) => stages.includes(s)
  const eqBars = [0, 1, 2, 3, 4].map(i => 5 + ((tick * (i + 3) * 7) % 12))

  return (
    <div className="lbs-wrap" style={{ position: 'relative', zIndex: 1, width: '100%', maxWidth: 1080, margin: 'auto' }}>

      {/* ── Cinematic HUD bar ── */}
      <div className="lbs-hud">
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, minWidth: 0 }}>
          <span className="lbs-rec-dot" />
          <span className="num" style={{ fontSize: 11, color: '#FF5C5C', letterSpacing: '.12em', fontWeight: 600 }}>REC</span>
          <span className="lbs-hud-pill">LIVE · 4K UHD · 60FPS</span>
          <div className="lbs-eq" style={{ display: 'flex', alignItems: 'flex-end', gap: 2, height: 16 }} aria-hidden>
            {eqBars.map((h, i) => (
              <span key={i} style={{ width: 3, height: h, borderRadius: 2, background: '#C7FF3D', opacity: .8, transition: 'height 120ms linear' }} />
            ))}
          </div>
        </div>
        <div className="lbs-hud-title eyebrow" style={{ color: '#86869A' }}>AI Build Studio — watch your website being written</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <span className="num" style={{ fontSize: 12, color: '#5A5A6E' }}>{mm}:{ss}:{ff}</span>
          <span className="num" style={{ fontSize: 13, color: '#C7FF3D', fontWeight: 600 }}>{progress}%</span>
        </div>
      </div>

      {/* Real progress bar */}
      <div style={{ height: 4, background: 'rgba(255,255,255,.06)', borderRadius: 99, overflow: 'hidden', margin: '10px 0 14px' }}>
        <div style={{ height: '100%', width: `${progress}%`, background: 'linear-gradient(90deg, #4F3DFF, #C7FF3D)', borderRadius: 99, boxShadow: '0 0 12px rgba(199,255,61,.4)', transition: 'width 500ms cubic-bezier(.25,1,.5,1)' }} />
      </div>

      <div className="lbs-studio">
        {/* ── Code editor pane ── */}
        <div className="lbs-editor cr-card cr-card-hairline">
          <div className="lbs-editor-chrome">
            <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#FF5F57' }} />
            <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#FEBC2E' }} />
            <span style={{ width: 10, height: 10, borderRadius: '50%', background: '#28C840' }} />
            <div style={{ display: 'flex', gap: 4, marginLeft: 10, minWidth: 0, overflow: 'hidden' }}>
              {FILES.map((f, i) => (
                <span key={f} className="num" style={{
                  fontSize: 10.5, padding: '4px 9px', borderRadius: 7, whiteSpace: 'nowrap',
                  color: i === currentFile ? '#F5F5FA' : '#5A5A6E',
                  background: i === currentFile ? 'rgba(255,255,255,.07)' : 'transparent',
                  border: `1px solid ${i === currentFile ? 'rgba(199,255,61,.25)' : 'transparent'}`,
                  transition: 'all 300ms',
                }}>
                  {i < currentFile ? '✓ ' : ''}{f}
                </span>
              ))}
            </div>
            <span className="num lbs-typing-badge" style={{ marginLeft: 'auto' }}>⌨ typing…</span>
          </div>
          <div ref={scrollRef} className="lbs-code num">
            {visible.map(l => (
              <div key={l.no} style={{ display: 'flex', minHeight: 19 }}>
                <span style={{ color: '#3A3A4A', width: 26, textAlign: 'right', marginRight: 12, flexShrink: 0, userSelect: 'none' }}>{l.no}</span>
                <span style={{ whiteSpace: 'pre', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                  {highlight(l.text, currentFile, style.accent)}
                  {l.partial && <span className="lbs-caret" />}
                </span>
              </div>
            ))}
          </div>
          {/* Decorative minimap */}
          <div className="lbs-minimap" aria-hidden>
            {Array.from({ length: 18 }).map((_, i) => (
              <span key={i} style={{
                display: 'block', height: 2, borderRadius: 2, marginBottom: 3,
                width: `${30 + ((i * 37) % 60)}%`,
                background: i / 18 < (safeLi / script.length) ? 'rgba(199,255,61,.35)' : 'rgba(255,255,255,.07)',
                transition: 'background 300ms',
              }} />
            ))}
          </div>
          {/* Stats strip */}
          <div className="lbs-stats num">
            <span><b style={{ color: '#F5F5FA' }}>{linesRef.current}</b> lines</span>
            <span><b style={{ color: '#F5F5FA' }}>{charsRef.current.toLocaleString()}</b> chars</span>
            <span><b style={{ color: '#C7FF3D' }}>{tokPerSec}</b> tok/s</span>
            <span><b style={{ color: '#F5F5FA' }}>{loop * FILES.length + currentFile + 1}</b> files</span>
          </div>
        </div>

        {/* ── Live browser preview pane ── */}
        <div className="lbs-preview cr-card cr-card-hairline" style={{ boxShadow: `0 0 60px ${style.glow}` }}>
          <div className="lbs-editor-chrome" style={{ gap: 8 }}>
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#5A5A6E" strokeWidth="2.5" strokeLinecap="round"><path d="M15 18l-6-6 6-6" /></svg>
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#5A5A6E" strokeWidth="2.5" strokeLinecap="round"><path d="M9 18l6-6-6-6" /></svg>
            <div className="num" style={{ flex: 1, fontSize: 10.5, color: '#86869A', background: 'rgba(255,255,255,.05)', borderRadius: 8, padding: '5px 10px', display: 'flex', alignItems: 'center', gap: 6, minWidth: 0 }}>
              <svg width="9" height="9" viewBox="0 0 24 24" fill="none" stroke="#22C08F" strokeWidth="3"><rect x="5" y="11" width="14" height="10" rx="2" /><path d="M8 11V7a4 4 0 0 1 8 0v4" /></svg>
              <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>binaapp.site/{name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}</span>
            </div>
            <span className="num" style={{ fontSize: 9.5, color: style.accent, border: `1px solid ${style.accent}44`, background: `${style.accent}14`, padding: '3px 8px', borderRadius: 99, letterSpacing: '.1em', whiteSpace: 'nowrap' }}>
              {style.name.toUpperCase()}
            </span>
          </div>

          <div className={`lbs-canvas${flash ? ' lbs-flash' : ''}`}>
            <div className="lbs-scanline" aria-hidden />
            {/* Nav */}
            {has('nav') && (
              <div className="lbs-rise" style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 12px', background: 'rgba(255,255,255,.04)', borderBottom: '1px solid rgba(255,255,255,.06)' }}>
                <span style={{ width: 14, height: 14, borderRadius: 5, background: style.accent, boxShadow: `0 0 10px ${style.accent}` }} />
                <span style={{ fontSize: 9, fontWeight: 700, color: '#F5F5FA', letterSpacing: '-0.01em' }}>{name}</span>
                <span style={{ marginLeft: 'auto', display: 'flex', gap: 6 }}>
                  {[24, 30, 26].map((w, i) => <span key={i} style={{ width: w, height: 4, borderRadius: 2, background: 'rgba(255,255,255,.18)' }} />)}
                  <span style={{ width: 34, height: 10, borderRadius: 99, background: style.accent, opacity: .9 }} />
                </span>
              </div>
            )}
            {/* Hero */}
            {has('heroTitle') && (
              <div style={{ padding: '18px 14px 16px', background: `linear-gradient(160deg, ${style.heroFrom}, ${style.heroTo})`, textAlign: 'center' }}>
                <div className="lbs-rise" style={{ fontSize: 13, fontWeight: 800, color: '#F5F5FA', letterSpacing: '-0.02em' }}>Welcome to {name}</div>
                {has('heroText') && <div className="lbs-rise" style={{ margin: '6px auto 0', width: '70%', height: 5, borderRadius: 3, background: 'rgba(255,255,255,.22)' }} />}
                {has('heroText') && <div className="lbs-rise" style={{ margin: '4px auto 0', width: '48%', height: 5, borderRadius: 3, background: 'rgba(255,255,255,.14)' }} />}
                {has('cta') && (
                  <div className="lbs-rise" style={{ display: 'inline-block', marginTop: 10, padding: '5px 14px', borderRadius: 99, background: style.accent, color: '#05050C', fontSize: 8, fontWeight: 700, boxShadow: `0 0 18px ${style.accent}` }}>
                    Order via WhatsApp
                  </div>
                )}
              </div>
            )}
            {/* Cards */}
            {(has('card1') || has('card2') || has('card3')) && (
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8, padding: '12px 12px 4px' }}>
                {(['card1', 'card2', 'card3'] as const).map(c => has(c) && (
                  <div key={c} className="lbs-rise" style={{ borderRadius: 8, overflow: 'hidden', border: '1px solid rgba(255,255,255,.07)', background: 'rgba(255,255,255,.03)' }}>
                    <div className="lbs-shimmer" style={{ height: 30, background: `linear-gradient(135deg, ${style.accent}33, rgba(255,255,255,.05))` }} />
                    <div style={{ padding: 6 }}>
                      <div style={{ width: '80%', height: 4, borderRadius: 2, background: 'rgba(255,255,255,.22)' }} />
                      <div style={{ width: '50%', height: 4, borderRadius: 2, background: `${style.accent}AA`, marginTop: 4 }} />
                    </div>
                  </div>
                ))}
              </div>
            )}
            {/* Contact */}
            {has('contact') && (
              <div className="lbs-rise" style={{ display: 'flex', gap: 6, padding: '8px 12px' }}>
                <span style={{ flex: 1, height: 14, borderRadius: 6, background: 'rgba(255,255,255,.06)', border: '1px solid rgba(255,255,255,.08)' }} />
                <span style={{ flex: 1, height: 14, borderRadius: 6, background: 'rgba(255,255,255,.06)', border: '1px solid rgba(255,255,255,.08)' }} />
                <span style={{ width: 42, height: 14, borderRadius: 6, background: style.accent, opacity: .9 }} />
              </div>
            )}
            {/* Footer */}
            {has('footer') && (
              <div className="lbs-rise" style={{ padding: '7px 12px', borderTop: '1px solid rgba(255,255,255,.06)', display: 'flex', justifyContent: 'center' }}>
                <span style={{ width: '55%', height: 4, borderRadius: 2, background: 'rgba(255,255,255,.14)' }} />
              </div>
            )}
            {/* Deployed badge on script completion */}
            {has('done') && (
              <div className="lbs-rise" style={{ position: 'absolute', top: 8, right: 8, display: 'flex', alignItems: 'center', gap: 5, padding: '4px 9px', borderRadius: 99, background: 'rgba(34,192,143,.15)', border: '1px solid rgba(34,192,143,.4)' }}>
                <Check size={9} stroke="#22C08F" strokeWidth={3} />
                <span className="num" style={{ fontSize: 8.5, color: '#22C08F', letterSpacing: '.08em' }}>STYLE READY</span>
              </div>
            )}
            {/* Empty-state boot text */}
            {!has('nav') && !has('heroTitle') && (
              <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <span className="num lbs-typing-badge" style={{ fontSize: 10 }}>◉ initializing {style.name.toLowerCase()} canvas…</span>
              </div>
            )}
          </div>

          {/* AI activity ticker */}
          <div className="lbs-ticker">
            <span className="ai-pulse" style={{ width: 6, height: 6, borderRadius: '50%', background: '#C7FF3D', boxShadow: '0 0 8px #C7FF3D', flexShrink: 0 }} />
            <span key={Math.floor(tick / 23) % TICKER.length} className="lbs-ticker-text num">
              {TICKER[Math.floor(tick / 23) % TICKER.length]}
            </span>
          </div>
        </div>
      </div>

      {/* ── Real pipeline steps (compact log) ── */}
      <div className="lbs-steps cr-card cr-card-hairline">
        {REAL_STEPS.map((step, i) => {
          const done = progress >= step.end
          const active = progress >= step.start && progress < step.end
          return (
            <div key={i} className="lbs-step" style={{ background: active ? 'rgba(199,255,61,.05)' : 'transparent' }}>
              <div style={{ width: 15, height: 15, borderRadius: '50%', flexShrink: 0, border: done ? 'none' : `1.5px solid ${active ? '#C7FF3D' : 'rgba(255,255,255,.1)'}`, background: done ? '#22C08F' : 'transparent', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                {done && <Check size={9} stroke="#05050C" strokeWidth={3.5} />}
                {active && <span className="ai-pulse" style={{ width: 5, height: 5, borderRadius: '50%', background: '#C7FF3D', boxShadow: '0 0 8px #C7FF3D' }} />}
              </div>
              <span style={{ fontSize: 12, color: done || active ? '#F5F5FA' : '#5A5A6E', fontWeight: active ? 500 : 400, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{step.label}</span>
            </div>
          )
        })}
      </div>

      {staleWarning && (
        <div className="banner-accent" style={{ marginTop: 14, marginBottom: 0, background: 'linear-gradient(90deg, rgba(255,176,32,.06), transparent)', border: '1px solid rgba(255,176,32,.22)', textAlign: 'left' }}>
          <div style={{ position: 'absolute', top: 0, bottom: 0, left: 0, width: 3, background: '#FFB020' }} />
          <span style={{ fontSize: 13, color: '#FFB020' }}>Progress appears stuck at {progress}%. The backend may be experiencing issues. Job may still complete.</span>
        </div>
      )}

      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 14, marginTop: 14, flexWrap: 'wrap' }}>
        <p style={{ fontSize: 12, color: '#5A5A6E', margin: 0 }}>This usually takes 45-90 seconds. Progress updates every 3 seconds.</p>
        {jobId && <p className="num" style={{ fontSize: 11, color: '#3A3A4A', margin: 0 }}>Job: {jobId.slice(0, 8)}…</p>}
      </div>
    </div>
  )
}
